
export const GET_ROUTE = 'GET_ROUTE';
export const GET_ROUTE_RESULT = 'GET_ROUTE_RESULT';

export const GET_ROUTES = 'GET_ROUTES';
export const GET_ROUTES_RESULT = 'GET_ROUTES_RESULT';

export const GET_ROUTE_STOPS = 'GET_ROUTE_STOPS';
export const GET_ROUTE_STOP_RESULT = 'GET_ROUTE_STOP_RESULT';

export const SEARCH_ROUTE_BY_NAME = 'SEARCH_ROUTE_BY_NAME';
export const SEARCH_ROUTE_BY_NAME_RESULT = 'SEARCH_ROUTE_BY_NAME_RESULT';

export const GET_STOP_COOR = '';
export const GET_STOP_COOR_RESULT = '';

export const GET_STOP_ROUTES = 'GET_STOP_ROUTES';
export const GET_STOP_ROUTES_RESULT = 'GET_STOP_ROUTES_RESULT';
